Add additional data field to user entity
drupalsocialinitiative/social_auth pull request #4
Opened 2017-07-12 10:24 UTC by himanshu-dixit

2017-07-16 02:15 UTC, gvso requested changes

2017-07-16 02:15 UTC, GVSO commented on src/SocialAuthUserManager.php
> +  public function authenticateUser($name, $email, $pluginId, $provider_user_id, $picture_url = FALSE, $data) {
Argument with default value must be at the end.

2017-07-16 02:15 UTC, GVSO commented on src/SocialAuthUserManager.php
> +        $this->addUserRecord($drupal_user->id(), $pluginId, $provider_user_id, $data);
You're not passing $data in line 172. It should be something like this.

2017-07-16 02:15 UTC, GVSO commented on src/SocialAuthUserManager.php
> +    if (!$social_auth_user)
You must enclose the block in brackets even if the block contains only one line of code.

2017-07-16 02:15 UTC, GVSO commented on src/SocialAuthUserManager.php
> +  public function addUserRecord($user_id, $pluginId, $provider_user_id, $user_data) {
You must add return tag in method documentation.

2017-07-16 02:15 UTC, GVSO commented on src/SocialAuthUserManager.php
>            array(
array() syntax must be replaced by [] due to a new coding standard. Please change all the matches in this file.

[Leave the code cleaner than you found it](http://pragmaticcraftsman.com/2011/03/the-boy-scout-rule/)

2017-07-16 02:15 UTC, GVSO commented on src/Entity/SocialAuth.php
>   *     "id" = "id",
Please run PHP CodeSniffer before any commits.

2017-07-16 10:04 UTC, himanshu-dixit commented on src/Entity/SocialAuth.php
>   *     "id" = "id",
Is there a problem with this file? PHPCS is not showing any violation for this particular file. Or were you making a general comment.

2017-07-16 10:07 UTC, himanshu-dixit reviewed
@GVSO I have addressed your review comments, Can you check it once again?

2017-07-16 10:07 UTC, himanshu-dixit commented on src/SocialAuthUserManager.php
> +        $this->addUserRecord($drupal_user->id(), $pluginId, $provider_user_id, $data);
Done.

2017-07-16 10:07 UTC, himanshu-dixit commented on src/SocialAuthUserManager.php
> +        $this->session->set($this->dataHandler->getSessionPrefix() . $session_key, NULL);
I'm still confused with this. I still think I might be making a mistake. Please, can you check if this part is correct?

2017-07-18 22:45 UTC, gvso requested changes

2017-07-18 22:45 UTC, GVSO commented on src/Entity/SocialAuth.php
>   *     "id" = "id",
It was a general comment

2017-07-18 22:45 UTC, GVSO commented on src/SocialAuthUserManager.php
> +   * @param JSON $data
JSON is not a PHP data type. 
$data is probably either a (serialized) string or an array. Don't exactly know how this work yet

2017-07-18 22:45 UTC, GVSO commented on src/SocialAuthUserManager.php
> +  public function authenticateUser($name, $email, $pluginId, $provider_user_id, $data, $picture_url = FALSE) {
To make it backward compatible, I would put $data with a default value at the end

2017-07-18 22:45 UTC, GVSO commented on src/SocialAuthUserManager.php
> +   * @param JSON $user_data
JSON data type doesn't exist

2017-07-18 22:45 UTC, GVSO commented on src/SocialAuthUserManager.php
> +        $this->session->set($this->dataHandler->getSessionPrefix() . $session_key, NULL);
You have a data handler object, you don't need a Symfony\Component\HttpFoundation\Session\Session object anymore. Instead, use the data handler to set, get, whatever data in session.

That being said, remove the $session service from this class

2017-07-24 15:45 UTC, himanshu-dixit commented
Closed, please see #5

2017-07-24 15:45 UTC, closed without merging